name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Specify your Go version

    - name: Build
      run: go build -v ./...

    # Add steps for running tests if you have them
    # - name: Test
    #   run: go test -v ./...